services:
    pg_store:
        image: postgres:17.2-alpine
        container_name: pg_store
        environment:
            POSTGRES_DB: ${APP_DB_DATABASE}
            POSTGRES_USER: ${APP_DB_USER}
            POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - ${APP_DB_PORT}:5432

volumes:
    pg-data: