// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error)
	CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) error
	ProductCreate(ctx context.Context, arg ProductCreateParams) (int32, error)
	Products(ctx context.Context, arg ProductsParams) ([]*ProductsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (int32, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (int32, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (int32, error)
	Users(ctx context.Context, arg UsersParams) ([]*UsersRow, error)
}

var _ Querier = (*Queries)(nil)
