// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShopOrder struct {
	ID          int32            `db:"id" json:"id"`
	UserID      *int32           `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamp `db:"order_date" json:"order_date"`
	TotalAmount *float64         `db:"total_amount" json:"total_amount"`
}

type ShopOrderproduct struct {
	OrderID   int32 `db:"order_id" json:"order_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

type ShopProduct struct {
	ID    int32    `db:"id" json:"id"`
	Name  *string  `db:"name" json:"name"`
	Price *float64 `db:"price" json:"price"`
}

type ShopUser struct {
	ID       int32   `db:"id" json:"id"`
	Name     *string `db:"name" json:"name"`
	Email    *string `db:"email" json:"email"`
	Password *string `db:"password" json:"password"`
}
